Android-x86 11 manifest: use clone-depth="1" for kernel
To avoid the following error:

GitCommandError: 'fetch --quiet --progress sf --force --prune --recurse-submodules=no --no-tags +refs/heads/kernel-5.4:refs/remotes/sf/kernel-5.4' on kernel failed

Due to connection issues:

fetch-pack: unexpected disconnect while reading sideband packetiB/s
fatal: early EOF
fatal: fetch-pack: invalid index-pack output
Change-Id: I5354e488a5c07b5d50ac2d7b3cac0ea7cbb07dc3